### PR TITLE
set .GlobalEnv during execution

### LINKED ISSUE #61: save.image doesn’t work
it doesn’t save everything. the docs say it’s the same as

```r
save(list = ls(all.names = TRUE), file = ".RData", envir = .GlobalEnv)
```

something here goes wrong. is it `.GlobalEnv` or `ls()`?

### PR DESCRIPTION
**Pull request by flying-sheep**
~~maybe~~ definitely fixes #61

### CODE REVIEW

File: R/execution.r [hunk 1]
```diff
@@ -37,9 +37,19 @@ namedlist <- function() {
 # This function copied from testthat, by Hadley Wickham. MIT licensed.
```
Comment (takluyver) [inline R/execution.r]: For completeness, this should now say 'originally copied'

Comment (takluyver) [inline R/execution.r]: Actually, I'll just merge and change that myself.

**Comment by takluyver** [comment]
I see it's gone from 'maybe' to 'definitely' now - thanks for testing.
